apiVersion: v1
kind: Service
metadata:
  name: loan-svc
  namespace: loan
spec:
  selector:
    app: loan
  type: ClusterIP
  ports:
    - name: loan-svc-http-port
      port: 8080
      targetPort: 8080

